apiVersion: v1
kind: ConfigMap
metadata:
  name: web-conf
data:
  default.conf: |-
    server {
      listen       80;
      server_name  _;

      index index.html index.htm index.php;

      location / {
        return 301 $scheme://$host:8080/icingaweb2$request_uri;
      }

      location ~ ^/icingaweb2/index\.php(.*)$ {
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/share/icingaweb2/public/index.php;
        fastcgi_param ICINGAWEB_CONFIGDIR /etc/icingaweb2;
        fastcgi_param REMOTE_USER $remote_user;
      }

      location ~ ^/icingaweb2(.+)? {
        alias /usr/share/icingaweb2/public;
        index index.php;
        try_files $1 $uri $uri/ /icingaweb2/index.php$is_args$args;
      }
    }