name: Build and Push Image
on:
  push:
    branches:
      - main

env:
  GITHUB: https://github.com
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: base
  IMAGE_NAME_ICINGA2: icinga-2
  IMAGE_NAME_ICINGADB: icinga-db
  IMAGE_NAME_ICINGAWEB: icinga-web
  DESCRIPTION_ICINGA2: Container Image for ICINGA 2 Monitoring Masters & Satellites
  DESCRIPTION_ICINGADB: Container Image for ICINGA DB Daemon
  DESCRIPTION_ICINGAWEB: Container Image for ICINGA SB Web PHP-FPM
  VENDOR: Axalon GmbH
  MAINTAINER: Alexander Plate <alexander.plate@axalon.ch>
  VERSION: 1
  REVISION: ${{ github.run_number }}
  LICENSE: GPL-2.0
  LICENSENOTE: Dieses Image enthält RHEL-Pakete, die nicht unter GPL-2.0 stehen. Sie dürfen nur mit einer gültigen RHEL-Subscription genutzt werden.

jobs:
  build:
    name: Build and push image
    runs-on: ubi8  # Self-hosted Runner nutzen 
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Checkout grafana repo
      uses: actions/checkout@v4
      with:
        repository: NETWAYS/icingaweb2-module-grafana
        path: grafana

    - name: Checkout nagvis repo
      uses: actions/checkout@v4
      with:
        repository: Icinga/icingaweb2-module-nagvis
        path: nagvis

    - name: Repositority Configuration
      run: |
        sed -i "s|username=|username=${{ secrets.ICINGA_USERNAME }}|g" ./src/${{ env.IMAGE_NAME_BASE }}/etc/yum.repos.d/ICINGA.repo
        sed -i "s|password=|password=${{ secrets.ICINGA_PASSWORD }}|g" ./src/${{ env.IMAGE_NAME_BASE }}/etc/yum.repos.d/ICINGA.repo
        echo "${{ secrets.RH_CLIENT_KEY }}" | tee ./src/${{ env.IMAGE_NAME_BASE }}/etc/pki/entitlement/client-key.pem > /dev/null
    
    - name: Build Base Image
      id: build-base-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}/${{ env.IMAGE_NAME_BASE }}
        tags: latest
        containerfiles: |
          ./containerfile/Containerfile.${{ env.IMAGE_NAME_BASE }}
        build-args: |
          IMAGENAMEBASE=${{ env.IMAGE_NAME_BASE }}
          IMAGENAMEICINGA2=${{ env.IMAGE_NAME_ICINGA2 }}
          IMAGENAMEICINGADB=${{ env.IMAGE_NAME_ICINGADB }}
          IMAGENAMEICINGAWEB=${{ env.IMAGE_NAME_ICINGAWEB }}

    - name: Build Icinga2 Image
      id: build-icinga2-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}/${{ env.IMAGE_NAME_ICINGA2 }}
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./containerfile/Containerfile.${{ env.IMAGE_NAME_ICINGA2 }}
        build-args: |
          IMAGENAME=${{ env.IMAGE_NAME_ICINGA2 }}
          BASEIMAGE=${{ env.IMAGE_NAME_BASE }}
          DESCRIPTION=${{ env.DESCRIPTION_ICINGA2 }}
          VENDOR=${{ env.VENDOR }}
          MAINTAINER=${{ env.MAINTAINER }}
          IMAGEURL=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME_ICINGAWEB }}
          REPOURL=${{ env.GITHUB }}/${{ github.repository }}
          VERSION=${{ env.VERSION }}
          REVISION=${{ env.REVISION }}
          LICENSE=${{ env.LICENSE }}
          LICENSENOTE=${{ env.LICENSENOTE }}

    - name: Build IcingaDB Image
      id: build-icingadb-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}/${{ env.IMAGE_NAME_ICINGADB }}
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./containerfile/Containerfile.${{ env.IMAGE_NAME_ICINGADB }}
        build-args: |
          IMAGENAME=${{ env.IMAGE_NAME_ICINGADB }}
          BASEIMAGE=${{ env.IMAGE_NAME_BASE }}
          DESCRIPTION=${{ env.DESCRIPTION_ICINGADB }}
          VENDOR=${{ env.VENDOR }}
          MAINTAINER=${{ env.MAINTAINER }}
          IMAGEURL=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME_ICINGAWEB }}
          REPOURL=${{ env.GITHUB }}/${{ github.repository }}
          VERSION=${{ env.VERSION }}
          REVISION=${{ env.REVISION }}
          LICENSE=${{ env.LICENSE }}
          LICENSENOTE=${{ env.LICENSENOTE }}

    - name: Build IcingaWeb Image
      id: build-icingaweb-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}/${{ env.IMAGE_NAME_ICINGAWEB }}
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./containerfile/Containerfile.${{ env.IMAGE_NAME_ICINGAWEB }}
        build-args: |
          IMAGENAME=${{ env.IMAGE_NAME_ICINGAWEB }}
          BASEIMAGE=${{ env.IMAGE_NAME_BASE }}
          DESCRIPTION=${{ env.DESCRIPTION_ICINGAWEB }}
          VENDOR=${{ env.VENDOR }}
          MAINTAINER=${{ env.MAINTAINER }}
          IMAGEURL=${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME_ICINGAWEB }}
          REPOURL=${{ env.GITHUB }}/${{ github.repository }}
          VERSION=${{ env.VERSION }}
          REVISION=${{ env.REVISION }}
          LICENSE=${{ env.LICENSE }}
          LICENSENOTE=${{ env.LICENSENOTE }}

          
    - name: Push Icinga2 To Registry
      id: push-icinga2-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-icinga2-image.outputs.image }}
        tags: ${{ steps.build-icinga2-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push IcingaDB To Registry
      id: push-icingadb-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-icingadb-image.outputs.image }}
        tags: ${{ steps.build-icingadb-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push IcingaWeb To Registry
      id: push-icingaweb-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-icingaweb-image.outputs.image }}
        tags: ${{ steps.build-icingaweb-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Icinga2 image url
      run: echo "Image pushed to ${{ steps.push-icinga2-to-registry.outputs.registry-paths }}"

    - name: Print IcingaDB image url
      run: echo "Image pushed to ${{ steps.push-icingadb-to-registry.outputs.registry-paths }}"

    - name: Print IcingaWeb image url
      run: echo "Image pushed to ${{ steps.push-icingaweb-to-registry.outputs.registry-paths }}"
